export const demoHistory = [
  {
    id: "h1",
    title: "Rack Added",
    description: "New Rack 'Rack Name' with 12 slots created",
    userName: "Admin Name",
    role: "admin",
    date: "2026-02-01T10:30:00Z",
  },
   {
    id: "h5",
    title: "Item Added",
    description: "NoteBooks (7) added to Rack Name - Slot 7",
    userName: "Manoj RS",
    role: "manager",
    date: "2025-12-29T09:10:00Z",
  },
  {
    id: "h2",
    title: "Slot Added",
    description: "Slot 2 added to Rack Name",
    userName: "Manager Name",
    role: "manager",
    date: "2026-02-01T10:35:00Z",
  },
  {
    id: "h3",
    title: "Slot Deleted",
    description: "Slot 2 removed from Rack Name",
    userName: "Admin Name",
    role: "admin",
    date: "2026-02-01T10:40:00Z",
  },
  {
    id: "h4",
    title: "Rack Deleted",
    description: "Rack 'Rack Name' deleted",
    userName: "Admin Name",
    role: "admin",
    date: "2025-12-31T09:10:00Z",
  },
 
  {
    id: "h6",
    title: "Item Deleted",
    description: "Note Book deleted from Rack C1 - Slot 1",
    userName: "Admin Name",
    role: "admin",
    date: "2025-12-23T09:10:00Z",
  },
  {
    id: "h7",
    title: "Item Returned",
    description: "1 × Note Book returned by User Name",
    userName: "Manager Name",
    role: "manager",
    date: "2025-12-14T09:10:00Z",
  },
];
